#https://hub.docker.com/r/privatebin/nginx-fpm-alpine/
version: '3.7'

services:
    privatebin:
        container_name: privatebin
        hostname: privatebin
        image: privatebin/nginx-fpm-alpine:latest
        restart: always
        user: 65534:65534
        read_only: true
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        ports:
            - '127.0.0.1:8055:8080'
        volumes:
            - ./privatebin-data:/srv/data
            - ./privatebin-data/conf.php:/srv/cfg/conf.php:ro
